### ISSUE TITLE
Onsite Payments Modal Popup missing payment methods

### ISSUE THREAD

**Issue by tjhunkin** [PayFast/payfast-php-sdk#2]
The payment modal opens, and it has the following text: "Choose your payment method:"

But there are no options available.

Any ideas?

**Comment by clairepf** [comment]
There are several reasons that could cause no payment methods to be available:

1) If the payment_method set to something like eft, but EFT disabled for your merchant
2) The amount falls outside min/max range of all payment methods enabled
3) The email/cell sent belongs to a banned user
4) It's a recurring billing setup, but credit card not enabled for merchant
5) Merchant has no payment methods enabled
6) Merchant account not verified and EFT disabled for merchant

Please drop a message if none of the above help, otherwise contact support@payfast.co.za

**Comment by tjhunkin** [comment]
Oops, was my fault, I set the return, cancel and notification URLs as HTTPS, but I didn't open the secure ngrok link to test from. It works now using your sample app, but not as yet from my Laravel implementation. Will tinker further...

**Comment by clairepf** [comment]
Great, glad you came right with the sample app.

**Comment by tjhunkin** [comment]
Was the minimum rand amount of R 5 that was the issue.

**Comment by clairepf** [comment]
Thanks for highlighting that, we will try to make that clearer.

**Comment by tjhunkin** [comment]
Thanks for the improvement to the error messages

**Comment by Sheldon-Knight** [comment]
@tjhunkin 


```php
composer require sheldonknight/laravelpayfast
```
